apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-api-vpbank-nfs
spec:
  storageClassName: pv-api-vpbank-nfs
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/home/data-pod/api-vpbank/source"
    server: "10.2.2.91"
