apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-fe-test-nfs
spec:
  storageClassName: pv-fe-test-nfs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/home/data-pod/mutosi-web/dist"
    server: "10.2.2.91"
