apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pos-nfs
spec:
  storageClassName: pv-pos-nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/home/data-pod/pos/pos-fe/dist"
    server: "10.2.2.91"
