apiVersion: v1
kind: ServiceAccount
metadata:
  name: tienp135
  namespace: dev-qas # thay doi namespace cho service account
secrets:
- name: tienp135-token-secret
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: tienp135
  name: tienp135-token-secret
  namespace: dev-qas # thay doi namespace cho secret tuong ung voi service account
type: kubernetes.io/service-account-token
