apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tienp135-devview-binding
  namespace: dev-qas # thay doi namespace
subjects:
- kind: ServiceAccount
  name: tienp135
  namespace: dev-qas
roleRef:
  kind: Role
  name: tienp135
  apiGroup: rbac.authorization.k8s.io
