apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-be-nfs-qas
  namespace: dev-qas
spec:
  storageClassName: pv-be-nfs-qas
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
