apiVersion: v1
kind: ServiceAccount
metadata:
  name: ducna-sa
  namespace: dev-qas # thay doi namespace cho service account
secrets:
- name: ducna-token-secret-dev-qas
---
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: ducna-sa
  name: ducna-token-secret-dev-qas
  namespace: dev-qas # thay doi namespace cho secret tuong ung voi service account
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ducna-sa
  namespace: test # thay doi namespace cho service account
secrets:
- name: ducna-token-secret-test
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: ducna-sa
  name: ducna-token-secret-test
  namespace: test # thay doi namespace cho secret tuong ung voi service account
type: kubernetes.io/service-account-token
